package org.ChatApp.model;

public enum RequestType {
    LOGIN,
    REGISTER,
    SEND_MESSAGE,
    GET_CONTACTS,
    GET_CONVERSATIONS,
    CREATE_CONVERSATION,
    ADD_MEMBER,
    REMOVE_MEMBER,
    UPDATE_PROFILE,
    GET_MESSAGE_HISTORY,
    SEND_FILE,
    RECEIVE_FILE,
    TYPING_STATUS,
    READ_RECEIPT,
    DELETE_MESSAGE,
    BLOCK_CONTACT,
    UNBLOCK_CONTACT,
    GET_BLOCKED_CONTACTS,
    REPORT_USER,
    LOGOUT
}
